# Generated by Django 4.0.6 on 2022-11-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, verbose_name='room_id')),
                ('room_no', models.IntegerField(verbose_name='room_no')),
            ],
        ),
        migrations.CreateModel(
            name='room_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas01', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas01')),
                ('gas02', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas02')),
                ('gas03', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas03')),
                ('gas04', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='gas04')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutter.rooms', verbose_name='room_id')),
            ],
        ),
    ]
